# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20160908_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRequest',
            fields=[
                ('id_no', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('requested_quantity', models.IntegerField()),
                ('requestee', models.CharField(max_length=100)),
                ('store_manager', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_of_request', models.DateField(auto_now=True)),
            ],
        ),
    ]
