# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_pendingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedRequest',
            fields=[
                ('id_no', models.UUIDField(default=0, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('requested_quantity', models.IntegerField()),
                ('requestee', models.CharField(max_length=100)),
                ('store_manager', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_of_request', models.DateField()),
                ('processed_by', models.CharField(max_length=100)),
                ('date_of_process', models.DateField(auto_now=True)),
                ('action', models.CharField(max_length=10)),
            ],
        ),
    ]
