# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_processedrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedrequest',
            name='acknowledgement',
            field=models.IntegerField(default=0),
        ),
    ]
