# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_processedrequest_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedrequest',
            name='approved_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
