# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='uname',
        ),
    ]
