# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20161007_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alternate_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mypost',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
