# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20161014_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('added_by', models.CharField(max_length=50)),
                ('modified_by', models.CharField(max_length=50)),
                ('is_active', models.IntegerField(default=1)),
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
