# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contact_person',
            field=models.CharField(default='test person', max_length=100),
            preserve_default=False,
        ),
    ]
