# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_vendor_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
