# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20161017_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytable',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
