# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('action', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('added_by', models.CharField(max_length=50)),
                ('approved_by', models.CharField(max_length=50)),
            ],
        ),
    ]
