# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_itemhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemhistory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
