# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20161023_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTableTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('quantity_inside', models.IntegerField()),
                ('quantity_outside', models.IntegerField()),
                ('minimum_quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('description', models.TextField()),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
