# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_inventorytabletemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytabletemp',
            name='creator',
            field=models.CharField(default='ruhshan.ahmed@yahoo.com', max_length=100),
            preserve_default=False,
        ),
    ]
