# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_inventorytabletemp_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytabletemp',
            name='action',
            field=models.CharField(default='create', max_length=100),
            preserve_default=False,
        ),
    ]
