# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_inventorytabletemp_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytabletemp',
            name='id',
        ),
        migrations.AddField(
            model_name='inventorytabletemp',
            name='req_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorytabletemp',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
