# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20161024_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytabletemp',
            name='req_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
