# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20161024_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytabletemp',
            name='req_id',
        ),
        migrations.AddField(
            model_name='inventorytabletemp',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
