# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20161024_0515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryTableTemp',
        ),
    ]
