# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_inventorytabletemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytabletemp',
            name='action',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorytabletemp',
            name='creator',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorytabletemp',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventorytabletemp',
            name='minimum_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytabletemp',
            name='quantity_inside',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytabletemp',
            name='quantity_outside',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytabletemp',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10),
        ),
    ]
