# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20161024_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytabletemp',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
