# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20161024_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
