# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_seccondarypassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
