# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemhistory',
            name='modified_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
