# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_itemhistory_modified_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedrequest',
            name='delivered_price',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
