# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_processedrequest_delivered_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default='Nick not set', max_length=50),
        ),
    ]
