# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_userprofile_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedrequest',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
