# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_auto_20161111_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequest',
            name='location',
            field=models.CharField(default='Non Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='processedrequest',
            name='location',
            field=models.CharField(default='Non Specified', max_length=100),
        ),
    ]
