# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_auto_20161115_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id_no', models.UUIDField(default=0, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50)),
                ('person', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('amnt', models.IntegerField()),
                ('occurace_date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
