# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_issues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='occurace_date',
            new_name='occurance_date',
        ),
    ]
