# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_auto_20161116_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='id_no',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
