# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_auto_20161116_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='id_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
