# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_auto_20161116_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytable',
            name='category',
            field=models.CharField(default='Old', max_length=100),
        ),
        migrations.AddField(
            model_name='inventorytabletemp',
            name='category',
            field=models.CharField(default='Old', max_length=100),
        ),
        migrations.AddField(
            model_name='issues',
            name='category',
            field=models.CharField(default='Old', max_length=100),
        ),
        migrations.AddField(
            model_name='itemhistory',
            name='category',
            field=models.CharField(default='Old', max_length=100),
        ),
        migrations.AddField(
            model_name='pendingrequest',
            name='category',
            field=models.CharField(default='Old', max_length=100),
        ),
        migrations.AddField(
            model_name='processedrequest',
            name='category',
            field=models.CharField(default='Old', max_length=100),
        ),
    ]
