# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_auto_20161118_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytable',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
